branches:
  only:
    - master
    - develop

language: ruby

rvm:
  - 2.3

install:
  - nvm install v8.4
  - nvm use v8.4
  - bundle install
  - yarn

cache: yarn

script:
  - yarn coverage
  - yarn lint

before_deploy:
  - yarn build

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation

deploy:
  provider: s3
  access_key_id:
    secure: UxFkyT37Jf8NjMjtybeIqdBxfH0/MPz8uhyQ/RlITuL/KpvBfUeapDH20xL8mIPqFrsMeRjWMOsdwDbWIeHNNlbaaJpR1/IaicUj/xM7p+g3BsFWxTwqwvIG8CuRl0jr64hMjJKby1ENrLzjxerutEMY4sm9Ubh/KWr+vzTBnxqxNNdpvZtcI0TWXRkGKg+aC/eeMxz+XdO83zMSVvgRDxVh8jJf5xsYYWzOtoJ9SKXQvuypjyhk4laxzwpIVlcbZGMjWV+braGvzHVvKP/NIapJJ2L1q0ch1pJtMbeuf6NRY8lb6JxSB81x1s69nPFwpBtPFzSkNjlEFo1cGRgSeB0lYaHlAXUC8XgDQCjAZYx0KiEcmSwDUWFf0xfJh9xxijob4UoB0IzEGaTg3/tew1UNfym3gdv0JHRDqHohhSsNOHzB1a55QZU/KuqNybuT8KdOI2irgjO9FVrK7F3yumV79iqiOK6ltsaEtSXn1Iwb9JaDDfaa/J3RjXXzNzYs1kzERULP5KNvLdL0E06uOTQZI7Y2EjyjetxSxJKpEQH7oC7/jbbDvVk7VZBH/hTqh4XsDTWi2qEXvojC0S9lDO0M66W3qrC7o+tgofJqeXXRDB+UnmvgfTOPiQSR6NMs4D7YN4Z3F7T3QHZkLDgN+EawGPZ0OeBB9R9vG8ugmLo=
  secret_access_key:
    secure: jMf6C3PnTzGRKjWlPBIjIJeaXjhFrVDXARv34+f74DmFAZ7vhASgnfYMWuoM0aoDUSzveF/RYvJ8EJH1jTl0jqWJglvLRCh7cRye3NfN41cBmTO4FD1/mTSsR1iLC++ZeLyUK3Y28X9iy2ZRv3s/QohhwW8FeJvmSFbiOS31xGgl1ZBGy+ULACU9kFRA9Zj8wjp0ATy6Fz97Esf5MQ8d8h3KSS+2FiBTdMb3K1zkBJQeDfl04U0biRfBzhUjBa3kjrB+eyUhjnSQb+CWV7q1MyKwVq7WcPEJDFISU5otxMOsW5J5+KDb8FoK+BiitMsk/LV9zm58zuUGcdcr7Z+9y6cliytGUzPfZ93av8/Q8AQ0o6qS3agq1g91CZM8gxPwZ5EEb9IS2fwwX17NbGRPWx33ZJtxldi5+SvES9PJf5450YwEqpLXrq4Ygi2g/7ThXgOHsB6M1SuqC7Q3CHGKw+xDGywqtfO63S0Ewszi4LkYge7Jpt93GYY9xiQ/sNRX+kQ/g5v8BWKX/NhIcaQsvfPXEx2dBN0W5F4y3kOxj1vDettwr/Oj+1aCMv5gQ1Vquk4i7J42Hde0PKaVAfkEcNOGuf9rk+TJ1OOSFT2dGmuefGhHFRq8+v+/h1dbRTbl3jxYp3wouj9t8rUg1tuZBWfRliFd03n8lL8a0wLrCuM=
  bucket: 61d24de9db.cidr.stanford.edu
  skip_cleanup: true
  acl: public_read
  region: us-west-2
  local_dir: _site
  on:
    branch: master
