name: Build

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'yarn'
    - name: Install Dependencies
      run: |
        bundle install --path vendor/bundle
        yarn install
    - name: Test
      run: |
        yarn coverage
        yarn lint
    - name: Build
      run: JEKYLL_ENV=production yarn build
    - name: Set Commit Message
      run:  echo "COMMIT_MESSAGE='Deploy from $(git log -n 1 --format="%h" HEAD) at $(date +"%Y-%m-%d %H:%M:%S %Z")'" >> $GITHUB_ENV
    - name: Deploy
      run: |
        git config --global user.email "simonjwiles@gmail.com"
        git config --global user.name "Simon Wiles"
        git fetch --force origin gh-pages:gh-pages
        git symbolic-ref HEAD refs/heads/gh-pages
        echo "noh.stanford.edu" > _site/CNAME
        git --work-tree _site reset --mixed --quiet
        git --work-tree _site add --all
        git --work-tree _site commit -m "$COMMIT_MESSAGE"
        git push origin gh-pages
