name: CI Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'yarn'

    - name: Install Dependencies
      run: |
        bundle install --path vendor/bundle
        yarn install

    - name: Test
      run: |
        yarn coverage
        yarn lint

    - name: Build
      run: JEKYLL_ENV=production yarn build
